### ISSUE TITLE
Конвертация qsp в обычный текст

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [QSPFoundation/qgen#1]
Всех приветствую. Очень хотелось бы,чтобы в qgeneral в диалоге сохранения можно было бы выбрать ти файлов .txt,и чтобы в этом случае текст конвертировался в читаемый формат,т.е чтобы его можно было бы открыть в любом текстовом редакторе и читать нормальные исходники игры,вместо абракадабры. Если такая возможность есть где-то,прошу меня простить,что я не заметил этого.

**Comment by hzdbyte** [comment]
Только что увидел вопрос. В меню должен быть "экспорт в формате TXT2GAM".
