### ISSUE TITLE
Сломан поиск/замена в v4.1.0-b4

### ISSUE THREAD

**Issue by Flamelis** [QSPFoundation/qgen#19]
Перешёл с версии 4.0.0-b1 на последнюю с архива qgen-v4.1.0-b4-win32.zip и обнаружил, что при замене не захватывается первый символ из графы поиска и съедается один последующий за ним.

Например:
Яблок+=10
С заменой "Яблок" на "Груш" превращается в:
ЯГруш=10

В прошлой версии с таким не сталкивался, об ошибке пишу на гитхаб впервые, если что не так, извиняюсь.

**Comment by hzdbyte** [comment]
Да, это было исправлено в QGen 4.1.0 beta 6.
